name: env_bec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - numpy=2.3.1
  - matplotlib=3.10.0
  - ffmpeg=4.3.1
  - cupy=13.4.1
  - argparse=1.4.0
  - tqdm=4.67.1
  - scikit-image=0.25.2
  - flask=3.0.3
  - pyyaml=6.0.1